name: Prepare test data

on:
    schedule:
        - cron: "0 0 1 * *" # run once a month to prevent artifact expiration
    workflow_dispatch:
# uncomment and adjust the branch name if you need to add new datasets to the artifact
#    push:
#        branches:
#            - main

jobs:
    prepare-data:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Download test datasets
              run: |
                  mkdir -p ./data
                  cd ./data

                  # the datasets are licensed as CC BY 4.0, as shown here
                  # https://www.10xgenomics.com/support/software/xenium-onboard-analysis/latest/resources/xenium-example-data

                  # 10x Genomics Xenium 2.0.0
                  curl -O https://cf.10xgenomics.com/samples/xenium/2.0.0/Xenium_V1_human_Breast_2fov/Xenium_V1_human_Breast_2fov_outs.zip
                  curl -O https://cf.10xgenomics.com/samples/xenium/2.0.0/Xenium_V1_human_Lung_2fov/Xenium_V1_human_Lung_2fov_outs.zip

                  # 10x Genomics Xenium 3.0.0 (5K) Mouse ileum, multimodal cell segmentation
                  # this file seems to be corrupted; skipping it for now
                  # curl -O https://cf.10xgenomics.com/samples/xenium/3.0.0/Xenium_Prime_MultiCellSeg_Mouse_Ileum_tiny/Xenium_Prime_MultiCellSeg_Mouse_Ileum_tiny.zip

                  # 10x Genomics Xenium 3.0.0 (5K) Mouse ileum, nuclear expansion
                  curl -O https://cf.10xgenomics.com/samples/xenium/3.0.0/Xenium_Prime_Mouse_Ileum_tiny/Xenium_Prime_Mouse_Ileum_tiny_outs.zip

                  # 10x Genomics Xenium 4.0.0 (v1) Human ovary, nuclear expansion
                  curl -O https://cf.10xgenomics.com/samples/xenium/4.0.0/Xenium_V1_Human_Ovary_tiny/Xenium_V1_Human_Ovary_tiny_outs.zip

                  # 10x Genomics Xenium 4.0.0 (v1) Human ovary, multimodal cell segmentation
                  curl -O https://cf.10xgenomics.com/samples/xenium/4.0.0/Xenium_V1_MultiCellSeg_Human_Ovary_tiny/Xenium_V1_MultiCellSeg_Human_Ovary_tiny_outs.zip

                  # 10x Genomics Xenium 4.0.0 (v1+Protein) Human kidney, multimodal cell segmentation
                  curl -O https://cf.10xgenomics.com/samples/xenium/4.0.0/Xenium_V1_Protein_Human_Kidney_tiny/Xenium_V1_Protein_Human_Kidney_tiny_outs.zip

                  # Spatial Genomics seqFISH v2
                  curl -O https://s3.embl.de/spatialdata/raw_data/seqfish-2-test-dataset.zip

            - name: Unzip files
              run: |
                  cd ./data
                  for file in *.zip; do
                      dir="${file%.zip}"
                      mkdir -p "$dir"
                      unzip "$file" -d "$dir"
                      rm "$file"
                  done

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: data
                  path: ./data
